<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "lyrics"
 *
 * Auto generated by Extension Builder 2014-09-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
    'title' => 'Lyrics',
    'description' => 'Lyrics and Artist Database',
    'category' => 'plugin',
    'author' => 'Markus Pircher',
    'author_email' => 'markus.pircher@netzolutions.eu',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.2.0',
    'constraints' => array(
        'depends' => array(
            'typo3' => '7.2.99 - 7.99.99',
        ),
        'conflicts' => array(),
        'suggests' => array(),
    ),
);